language: c
cache: apt
compiler:
    - gcc
    - clang
before_install:
    - sudo apt-get update -qq
install:
    - sudo apt-get install -y libev-dev
before_script:
    - "sed -i -e s/69/67/g configure.ac"
    - "autoreconf -i"
script:
    - "./configure --prefix=/usr"
    - "make"
    - "make DESTDIR=/tmp/dest install"
branches:
    only:
        - master
